{
    "name": "Micron HVAC Clean Room",
    "summary": "Clean room validation jobs, readings, and certificates",
    "version": "18.0.1.0.0",
    "category": "Services",
    "author": "ASD RAKESH",
    "website": "https://www.asdsoftwares.com",
    "license": "LGPL-3",
    "depends": ["base", "mail", "contacts"],
    "data": [
        "security/security.xml",
        "security/ir.model.access.csv",
        "data/job_sequence.xml",
        "data/sop_data.xml",
        "views/micron_menus.xml",
        "views/equipment_views.xml",
        "views/clean_room_area_views.xml",
        "views/sop_template_views.xml",
        "views/job_order_views.xml",
        "views/air_velocity_views.xml",
        "report/micron_sop_report.xml",
        "report/micron_test_certificate_report.xml",
    ],
    "application": True,
    "installable": True,
}
